apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.storage.cloudcarbonfootprint.org
spec:
  group: storage.cloudcarbonfootprint.org
  names:
    kind: XBuckets
    plural: xbuckets
  claimNames:
    kind: Bucket
    plural: buckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          status:
            type: object
            properties:
              arn:
                type: string
    additionalPrinterColumns:
    - name: ARN
      type: string
      jsonPath: .status.arn